import type { Metadata } from "next";
import "./globals.css";
import "tailwindcss/tailwind.css";
import { ApolloProvider } from "../providers/apollo"
import { Footer } from "../features/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ApolloProvider>{children}</ApolloProvider>
        <Footer />
      </body>
    </html>
  );
}
